#!/bin/bash

# Archimedes system settings

# Set up Node Version Manager (installed from AUR)
source /usr/share/nvm/init-nvm.sh

# If the .xsession-errors file is not a symbolic link, delete it and create it as such
if [ ! -h $HOME/.xsession-errors ]; then
 /bin/rm $HOME/.xsession-errors
 ln -s /dev/null $HOME/.xsession-errors
fi

